const API_ROUTES = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    logout: '/auth/logout',
    me: '/auth/me',
    user: '/user',
  },
  users: {
    index: '/users',
    store: '/users',
    show: (id) => `/users/${id}`,
    update: (id) => `/users/${id}`,
    destroy: (id) => `/users/${id}`,
    toggleStatus: (id) => `/users/${id}/toggle-status`,
    changePassword: (id) => `/users/${id}/change-password`,
  },
  customers: {
    index: '/customers',
    store: '/customers',
    show: (id) => `/customers/${id}`,
    update: (id) => `/customers/${id}`,
    destroy: (id) => `/customers/${id}`,
    toggleStatus: (id) => `/customers/${id}/toggle-status`,
  },
  products: {
    index: '/products',
    store: '/products',
    show: (id) => `/products/${id}`,
    update: (id) => `/products/${id}`,
    destroy: (id) => `/products/${id}`,
  },
  orders: {
    index: '/orders',
    store: '/orders',
    show: (id) => `/orders/${id}`,
    update: (id) => `/orders/${id}`,
    destroy: (id) => `/orders/${id}`,
    invoice: (id) => `/orders/${id}/invoice`,
    shippingLabel: (id) => `/orders/${id}/shipping-label`,
    calculateShipping: '/orders/calculate-shipping',
  },
  vouchers: {
    index: '/vouchers',
    store: '/vouchers',
    show: (id) => `/vouchers/${id}`,
    update: (id) => `/vouchers/${id}`,
    destroy: (id) => `/vouchers/${id}`,
    toggleStatus: (id) => `/vouchers/${id}/toggle-status`,
    validate: '/vouchers/validate',
    active: '/vouchers-active',
  },
  expenses: {
    index: '/expenses',
    store: '/expenses',
    show: (id) => `/expenses/${id}`,
    update: (id) => `/expenses/${id}`,
    destroy: (id) => `/expenses/${id}`,
    categories: '/expense-categories',
    summary: '/expense-summary',
    exportExcel: '/expenses/export-excel',
  },
  reports: {
    sales: '/reports/sales',
    stock: '/reports/stock',
    userPerformance: '/reports/user-performance',
    payments: '/reports/payments',
    exportSales: '/reports/export-sales',
  },
  roles: {
    index: '/roles',
    store: '/roles',
    show: (id) => `/roles/${id}`,
    update: (id) => `/roles/${id}`,
    destroy: (id) => `/roles/${id}`,
    toggleStatus: (id) => `/roles/${id}/toggle-status`,
  },
  couriers: {
    index: '/couriers',
    store: '/couriers',
    show: (id) => `/couriers/${id}`,
    update: (id) => `/couriers/${id}`,
    destroy: (id) => `/couriers/${id}`,
    toggleStatus: (id) => `/couriers/${id}/toggle-status`,
  },
  paymentBanks: {
    index: '/payment-banks',
    store: '/payment-banks',
    show: (id) => `/payment-banks/${id}`,
    update: (id) => `/payment-banks/${id}`,
    destroy: (id) => `/payment-banks/${id}`,
    toggleStatus: (id) => `/payment-banks/${id}/toggle-status`,
  },
  salesChannels: {
    index: '/sales-channels',
    store: '/sales-channels',
    show: (id) => `/sales-channels/${id}`,
    update: (id) => `/sales-channels/${id}`,
    destroy: (id) => `/sales-channels/${id}`,
    toggleStatus: (id) => `/sales-channels/${id}/toggle-status`,
    options: '/sales-channels/options',
  },
  stockMovements: {
    index: '/stock-movements',
    store: '/stock-movements',
    show: (id) => `/stock-movements/${id}`,
    update: (id) => `/stock-movements/${id}`,
    destroy: (id) => `/stock-movements/${id}`,
  },
  stockOpnames: {
    index: '/stock-opnames',
    store: '/stock-opnames',
    show: (id) => `/stock-opnames/${id}`,
    update: (id) => `/stock-opnames/${id}`,
    destroy: (id) => `/stock-opnames/${id}`,
    start: (id) => `/stock-opnames/${id}/start`,
    complete: (id) => `/stock-opnames/${id}/complete`,
    finalize: (id) => `/stock-opnames/${id}/finalize`,
  },
  courierRates: {
    index: '/courier-rates',
    store: '/courier-rates',
    show: (id) => `/courier-rates/${id}`,
    update: (id) => `/courier-rates/${id}`,
    destroy: (id) => `/courier-rates/${id}`,
    import: '/courier-rates/import',
    importStatus: (jobId) => `/courier-rates/import-status/${jobId}`,
    activeImports: '/courier-rates/active-imports',
    destinations: '/courier-rates/destinations',
    serviceTypes: '/courier-rates/service-types',
    getCouriers: '/courier-rates/couriers',
  },
};

export default API_ROUTES;
